### PR TITLE
Switch to SHA2 and constant-time comparisons

### PR DESCRIPTION
**Pull request by jedisct1**

### CODE REVIEW

**Comment by benallfree** [comment]
What motivated you to fix this in 3 places? :)

**Comment by jedisct1** [comment]
I wrote this class a while back, someone mentioned the non constant-time comparison, I fixed the original code, looked for projects possibly using the code, found yours, submitted the same fix as the one applied to the original code.

**Comment by jedisct1** [comment]
Haha, looks like he also submitted a similar patch :)

**Comment by jedisct1** [comment]
Still, you may want to switch from MD5 to SHA2.

**Pull request closed without merging**
